alternativeSigns: {  }
exchangeRates: {  }
currencyCode: FKP
currencyNumber: '238'
sign: Â£
subunits: 100
label: 'Falkland Islands Pound'
usage:
    - { start: '1901-01-01', end: '', countryCode: FK }
