alternativeSigns: {  }
exchangeRates: {  }
currencyCode: LKR
currencyNumber: '144'
sign: â‚¨
subunits: 100
label: 'Sri Lankan rupee'
usage:
    - { usageFrom: '1978-05-22', usageTo: '', countryCode: LK }
