alternativeSigns: {  }
exchangeRates: {  }
currencyCode: SHP
currencyNumber: '654'
sign: Â£
subunits: 100
label: 'Saint Helena pound'
usage:
    - { usageFrom: '1917-02-15', usageTo: '', countryCode: SH }
