alternativeSigns: {  }
exchangeRates: {  }
currencyCode: ALK
currencyNumber: null
sign: Â¤
subunits: 100
label: 'Albanian lek'
usages:
    - { start: '1946-11-01', end: '1965-08-16', countryCode: AL }
