alternativeSigns: {  }
exchangeRates:
    KRH: '10'
currencyCode: KRW
currencyNumber: '410'
sign: â‚©
subunits: 100
label: 'South Korean won'
usage:
    - { ISO8601From: '1962-06-10', ISO8601To: '', ISO3166Code: KR }
