alternativeSigns: {  }
exchangeRates:
    SDD: '100'
currencyCode: SDG
currencyNumber: '938'
sign: â‚¤
subunits: 100
label: 'Sudanese pound'
usage:
    - { ISO8601From: '2007-01-10', ISO8601To: '', ISO3166Code: SD }
    - { ISO8601From: '2007-01-10', ISO8601To: '2011-09-01', ISO3166Code: SS }
