alternativeSigns: {  }
exchangeRates: {  }
currencyCode: CSK
currencyNumber: '200'
sign: KÄs
subunits: 100
label: 'Czechoslovak koruna'
usage:
    - { usageFrom: '1953-06-01', usageTo: '1993-03-01', countryCode: CZ }
    - { usageFrom: '1953-06-01', usageTo: '1992-12-31', countryCode: SK }
