alternativeSigns: {  }
exchangeRates: {  }
currencyCode: CSK
currencyNumber: '200'
sign: KÄs
subunits: 100
label: 'Czechoslovak koruna'
usage:
    - { start: '1953-06-01', end: '1993-03-01', countryCode: CZ }
    - { start: '1953-06-01', end: '1992-12-31', countryCode: SK }
